export const API_BASE_URL = import.meta.env.VITE_API_GATEWAY_URL || 'http://localhost:3000';
export const WS_URL = import.meta.env.VITE_WS_URL || 'ws://localhost:3000';
export const APP_NAME = import.meta.env.VITE_APP_NAME || 'CommerceSphere';
export const APP_VERSION = import.meta.env.VITE_APP_VERSION || '1.0.0';

export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCT_REVIEWS: '/products/:id/reviews',
  CATEGORIES: '/categories',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  TRACK_ORDER: '/track-order',
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  COMPARE: '/compare',
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_EDIT: '/admin/products/:id/edit',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAIL: '/admin/orders/:id',
  ADMIN_INVENTORY: '/admin/inventory',
  ADMIN_USERS: '/admin/users',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_VENDORS: '/admin/vendors',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_SETTINGS: '/admin/settings',
  SELLER: '/seller',
  SELLER_PRODUCTS: '/seller/products',
  SELLER_PRODUCT_NEW: '/seller/products/new',
  SELLER_PRODUCT_EDIT: '/seller/products/:id/edit',
  SELLER_ORDERS: '/seller/orders',
  SELLER_INVENTORY: '/seller/inventory',
  SELLER_ANALYTICS: '/seller/analytics',
  SELLER_REVIEWS: '/seller/reviews',
  INVOICE: '/orders/:id/invoice',
  ENTERPRISE: '/enterprise',
  DEVELOPER: '/developer',
  SUPPORT: '/support',
  MAINTENANCE: '/maintenance',
} as const;

export const API_TAGS = {
  AUTH: 'Auth',
  PRODUCTS: 'Products',
  PRODUCT: 'Product',
  CART: 'Cart',
  ORDERS: 'Orders',
  ORDER: 'Order',
  WISHLIST: 'Wishlist',
  USER: 'User',
  PROFILE: 'Profile',
  REVIEWS: 'Reviews',
  SEARCH: 'Search',
  ANALYTICS: 'Analytics',
  NOTIFICATIONS: 'Notifications',
  VENDORS: 'Vendors',
  ROLES: 'Roles',
} as const;

export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'access_token',
  REFRESH_TOKEN: 'refresh_token',
  USER: 'user',
  CART: 'cart',
  WISHLIST: 'wishlist',
  THEME: 'theme',
} as const;
